### ISSUE TITLE
Add an option to disable param escaping

### ISSUE THREAD

**Issue by hcpss-banderson** [adambrett/php-shell-wrapper#10]
Moving files with the mv command and a wildcard fails because of added quotes. Here's an example:

```php
$moveCommand = new CommandBuilder('mv');
$moveCommand
    ->addParam('/my/source/*')
    ->addParam('/my/destination');

$shell = new ShellExec();
$shell->run($moveCommand);
```

The command that is actually run is this:

```
mv '/my/source/*' '/my/destination'
```

Which throws this error:

```
mv: rename /my/source/* to /my/destination/*: No such file or directory
```

I guess what's happening is the single quotes are disabling the wildcard interpretation. I think a way to fix this is to allow developers to disable escaping when adding a param.

**Comment by hcpss-banderson** [comment]
Right now my workaround is to use "addSubCommand" instead of "addParam".

**Comment by adambrett** [comment]
@hcpss-banderson I've given this a little thought and I'm happy with how it works, and the workaround.

I think of a glob path as a sub command because of the way it's interpreted in the shell (basically all files are found and then passed to the command one at a time as actual params, as if it were a loop).

I think the distinction between sub-command and param works well in this instance.

If there's another use case for this let me know and I'll give it some more thought!

**Comment by hcpss-banderson** [comment]
Fair enough. Thanks!
