### ISSUE TITLE
Add Runner interfaces hierarchy 

### ISSUE THREAD

**Issue by Bukharovsi** [adambrett/php-shell-wrapper#22]
I am confused when i using Runner interface. I try to explain the problem.
My code is:

```
      public function showFileList(Runner $runner) 
      {
           $cmd = new Command('ls')
           $exitCode = $this->runner->run($cmd);

           if (0 != $exitCode) {
               throw ExecutionCommandException::executionFauled($cmd, $runner->getStandardOut());
            }
      }
```

If execution failed i wanna get output and error string. But `Runner` Interface does't contains this methods. And this is true way.
But how can i gets this messages? Obvious way is `public function showFileList(StandardOut $runner) ` but it does't contains method `run()`. And Does't contains `getStandardError` too.

I offer add hierarchy of Runners:
```
    interface ReturnedValueRunner extends Runner { ...

    interface ReturnedValueRunnerWithStandardOutput extends ReturnedValueRunner { ...

    interface ReturnedValueRunnerWithStandardAndErrorOutput extends ReturnedValueRunnerWithStandardOutput { ...
```

I know, this is not graceful solution, but i dont know another way. May be i missed something?

**Comment by adambrett** [comment]
The runners themselves all behave differently, and deliberately so, because they map to the php functions that are underneath. If you require both methods in a single call, then you care about which low-level php function you're using, so you should type hint on the runner class itself, rather than the interface.

Thanks
