### ISSUE TITLE
Argument with = delimiter

### ISSUE THREAD

**Issue by claygorman** [adambrett/php-shell-wrapper#25]
Hey there,

I was wondering how I could do an argument with a = instead of a space?

`--arg=value` vs `--arg value`

**Comment by adambrett** [comment]
Like so:

```php
<?php

namespace YourApp\Command;

class Argument extends AdamBrett\ShellWrapper\Command\Argument
{
    protected function getValuesAsString()
    {
        $values = array_map('escapeshellarg', $this->values);
        $prefix = sprintf('%s%s=', static::PREFIX, $this->name);
        return $prefix . join("=${prefix}", $values);
    }
}
```

Usage:

```php
use YourApp\Command\Argument;

$shell->addArgument(new Argument('exclude', ['.git*', 'cache'])); 
```

If you wanted to use it with a builder, you'd need to create a custom builder class in your app that extends `AdamBrett\ShellWrapper\Command\Builder` and overloads the `addArgument` method to use your new class instead of the original:

```php
<?php
namespace YourApp\Command;

class Builder extends \AdamBrett\ShellWrapper\Command\Builder
{
    public function addArgument($name, $value = null)
    {
        $this->command->addArgument(new Argument($name, $value));
        return $this;
    }
}
```

I'd also be happy to accept a pull request that modifies https://github.com/adambrett/php-shell-wrapper/blob/master/src/Command/Value.php#L35 to use a class constant (defaulting to space), which would make overriding this much simpler:

```php
abstract class Value {
    const ASSIGNER = ' ';

    // ...
    protected function getValuesAsString()
    {
        $values = array_map('escapeshellarg', $this->values);
        $prefix = sprintf('%s%s%s', static::PREFIX, static::ASSIGNER, $this->name);
        return $prefix . join(sprintf("%s%s", static::ASSIGNER, $prefix), $values);
    }
}
```

Then your app's argument class could be as simple as:

```php
<?php

namespace YourApp\Command;

class Argument extends AdamBrett\ShellWrapper\Command\Argument
{
    const ASSIGNER = '=';
}
```

But it would need some tests, and to follow the guidelines here: https://github.com/adambrett/php-shell-wrapper#contributing

Hope this helps!
