### ISSUE TITLE
Send to background

### ISSUE THREAD

**Issue by Ortix92** [adambrett/php-shell-wrapper#6]
I would like to use your package to send scripts to the background. This way I can keep executing the php script without the shell script blocking. Normally I use `> /dev/null 2>/dev/null &`. Anyway to achieve this?

**Comment by adambrett** [comment]
Sure, something like this should work:

```php
<?php

namespace Your\App\Commands;

use AdamBrett\ShellWrapper\Command;

class BackgroundCommand extends Command
{
    public function __toString()
    {
        return parent::__toString() . '> /dev/null 2>/dev/null &';
    }
}
```
Usage:

```php
$shell = new Exec();
$command = new BackgroundCommand('some-command');
$shell->run($command);
```

This is untested, if it doesn't solve your problem please let me know and I'll see what I can do.

**Comment by obarcelonap** [comment]
Hello Adam, first of all thank you for your effort.
Why not to add this feature to the package? I think it's very interesting...

Regards,

**Comment by adambrett** [comment]
@obarcelonap: thanks for the comment. It's something I'm considering, but the api (maybe something like `$shell->exec($command)->sendToBackground()`) and method has to be right (using `>/dev/null` doesn't feel right to me), so I don't want to rush it.

In the mean time this method works, but I would also recommend that long-running user/web-initiated tasks should be run from a queue+worker (e.g. beanstalkd) rather than run by your application directly.

**Comment by obarcelonap** [comment]
@adambrett I think that offering all the options to the coder should be the main goal of the library. Without using this library, I can execute php's exec() function sending it to background appending at the "&" at the end of the command, why not to expose this functionality? Just I want to use it in more OOP way.
I'm aware of your concerns about web environment , but what happens if I want to use your library in my command line script?

Never mind, for now, I'm using your suggested code and it works nice. I'll watch for future updates. 
Congratulations for your work.

**Comment by adambrett** [comment]
The main goal of the library is to provide a unit-testable interface to the low level shell functions, which is why I want to be careful about any new APIs I add, for example:

My current thinking is that something like the following would be quite nice:

```php
$shell->exec($command)->sendToBackground()
```

but I don't know the best way to implement this as it would be almost completely re-working how the shell executors currently work, and it also makes it slightly harder to test.

On the other-hand, I could introduce a new type of command as there are a couple of other custom types of command I've had to write for specific applications.  Then it would work as the example above. This would be pretty easy to test, as you could just mock or stub whichever command you wanted to use, however this has an issue with the use of the command builder as I would need to introduce bc-breaking changes to make this method work and maintain a nice API.

I am thinking about it all and will be adding it at some point, but it really does need some proper thought and experimentation so that we get the best solution going forward!
